name: Ceretech
favicon: null
layout_spectrum: 0.24156163493171334
typography_spectrum: 0.31270366278477013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.017972226487472653
  lightness: 0.8975285501219332
  saturation: 0.32610097294673324
  rhythmicContrast: 0.7502551465295255
purpose: []
