name: Ceretech
favicon: null
layout_spectrum: 0.24609
typography_spectrum: 0.99458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#051922'
    - '#00a1e4'
    - '#017aac'
    - '#58595b'
    - '#024f70'
  brandStrength: 0.017972226487472653
  lightness: 0.8975285501219332
  saturation: 0.32610097294673324
  rhythmicContrast: 0.7502551465295255
purpose: []
